# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restr_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
