# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restr_ratings', '0003_auto_20170307_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='environ_score',
            new_name='ambience_score',
        ),
    ]
